Dictionnaire = {
    "EN" : {
    'DataLoaded' : "Data are loaded in the system.",
    'CantFindBuild' : "Can't find a build in my database fitting your criterias.",
    'CantCalculateEffects' : "Cannot calculate the effects of the cells",
    'Notes_part1' : "All **UrskaBot** builds come from the [Official Metasheet](https://docs.google.com/spreadsheets/d/1-I4LQ_8uNqV9LuybXhz2wjmcPeTNNGWRZ-kFjsckwtk/edit#gid=0).",
    'Notes_part2' : "Those builds are standard and optimized ones. If they didn't fit your needs, you can follow the link to the metasheet or make a request in a dedicated channel.",
    'SummaryRequest' : "__Summary of your request :__",
    "Type" : "- Type :",
    "Weapon" : "- Weapon :",
    "Element" : "- Element :",
    "BuildTitleRequest" : "Build Request",
    "Link" : "__Link__",
    "Cells" : "__Cells__",
    "Notes" : "__Notes__",
    "ClickHere" : "Click here -> [Dauntless-Builder.com]",
    "Request" : "Request n°",
    "TrialNotSetup" : "We are not able to provide you with a build as current Trial is not setup or builds are not populated in the sheet",
    "TrialTitleRequest" : "Trial : ",
    "Trials_Notes_part1" : "All **UrskaBot** trial builds are __mainly solobuilds__ and come from the [Trial Official Metasheet](https://docs.google.com/spreadsheets/d/1Kv3nlr7y5DJB_olhATqXXh-jPCkDygNCVyHkDwllTsc/edit#gid=0).",
    "Trials_Notes_part2" : "You can follow the link above in order to get other builds and/or pots information and tips."
    },
    "FR" : {
    'DataLoaded' : "Les données sont chargées dans le système.",
    'CantFindBuild' : "Je ne trouve pas de build dans ma base de données qui corresponde à votre demande",
    'CantCalculateEffects' : "Je n'arrive pas à calculer les effets des cellules",
    'Notes_part1' : "Tous les builds d'**UrskiBot** proviennent du [Metasheet Officiel](https://docs.google.com/spreadsheets/d/1-I4LQ_8uNqV9LuybXhz2wjmcPeTNNGWRZ-kFjsckwtk/edit#gid=0).",
    'Notes_part2' : "Ces builds sont standards et optimisés. S'ils ne répondent pas à votre requête, vous pouvez accéder à la Metasheet avec le lien ci-dessus, ou faire une demande dans le salon dédié",
    'SummaryRequest' : "__Résumé de votre demande :__",
    "Type" : "- Type :",
    "Weapon" : "- Arme :",
    "Element" : "- Élement :",
    "BuildTitleRequest" : "Requête de build",
    "Link" : "__Lien__",
    "Cells" : "__Cellules__",
    "Notes" : "__Remarques__",
    "ClickHere" : "Cliquez ici -> [Dauntless-Builder.fr]",
    "Request" : "Requête n°",
    "TrialNotSetup" : "Nous ne pouvons pas vous fournir de build car l'Épreuve actuelle n'est pas définie ou que les builds ne sont pas enregistrés dans le Metasheet Officiel.",
    "TrialTitleRequest" : "Épreuve : ",
    "Trials_Notes_part1" : "Tous les builds d'Épreuve d'**UrskiBot** sont des builds __principalement solo__ et proviennent du [Metasheet Officiel des Épreuves](https://docs.google.com/spreadsheets/d/1Kv3nlr7y5DJB_olhATqXXh-jPCkDygNCVyHkDwllTsc/edit#gid=0) (EN).",
    "Trials_Notes_part2" : "Vous pouvez suivre le lien ci-dessus afin d'accéder à d'autres builds, des astuces ou des informations sur les toniques à utiliser."
    }
}