Dictionnaire = {
    "EN" : {
    'DataLoaded' : "Data are loaded in the system.",
    'CantFindBuild' : "Can't find a build in my database fitting your criterias.",
    'CantCalculateEffects' : "Cannot calculate the effects of the cells",
    'Notes_part1' : "All **UrskaBot** builds come from the [Official Metasheet](https://docs.google.com/spreadsheets/d/1-I4LQ_8uNqV9LuybXhz2wjmcPeTNNGWRZ-kFjsckwtk/edit#gid=0).",
    'Notes_part2' : "Those builds are standard and optimized ones. If they didn't fit your needs, you can follow the link to the metasheet or make a request in a dedicated channel.",
    'SummaryRequest' : "__Summary of your request :__",
    "Type" : "- Type :",
    "Weapon" : "- Weapon :",
    "Element" : "- Element :",
    "BuildTitleRequest" : "Build Request",
    "Link" : "__Link__",
    "Cells" : "__Cells__",
    "Notes" : "__Notes__",
    "ClickHere" : "Click here ->[Dauntless-Builder.com]",
    "Request" : "Request n°",
    "TrialNotSetup" : "We are not able to provide you with a build as current Trial is not setup or builds are not populated in the sheet",
    "TrialTitleRequest" : "Trial : ",
    "Trials_Notes_part1" : "All **UrskaBot** trial builds come from the [Trial Official Metasheet](https://docs.google.com/spreadsheets/d/1Kv3nlr7y5DJB_olhATqXXh-jPCkDygNCVyHkDwllTsc/edit#gid=0).",
    "Trials_Notes_part2" : "You can follow the link above in order to get other builds and/or pots information and tips."
    },
    "FR" : {
    'DataLoaded' : "Les données sont chargées dans le système.",
    'CantFindBuild' : "Can't find a build in my database fitting your criterias.",
    'CantCalculateEffects' : "Cannot calculate the effects of the cells",
    'Notes_part1' : "All **UrskaBot** builds come from the [Official Metasheet](https://docs.google.com/spreadsheets/d/1-I4LQ_8uNqV9LuybXhz2wjmcPeTNNGWRZ-kFjsckwtk/edit#gid=0).",
    'Notes_part2' : "Those builds are standard and optimized ones. If they didn't fit your needs, you can follow the link to the metasheet or make a request in a dedicated channel.",
    'SummaryRequest' : "__Summary of your request :__",
    "Type" : "- Type :",
    "Weapon" : "- Weapon :",
    "Element" : "- Element :",
    "BuildTitleRequest" : "Build Request",
    "Link" : "__Link__",
    "Cells" : "__Cells__",
    "Notes" : "__Notes__",
    "ClickHere" : "Click here ->[Dauntless-Builder.com]",
    "Request" : "Request n°",
    "TrialNotSetup" : "We are not able to provide you with a build as current Trial is not setup or builds are not populated in the sheet",
    "TrialTitleRequest" : "Trial : ",
    "Trials_Notes_part1" : "All **UrskaBot** trial builds come from the [Trial Official Metasheet](https://docs.google.com/spreadsheets/d/1Kv3nlr7y5DJB_olhATqXXh-jPCkDygNCVyHkDwllTsc/edit#gid=0).",
    "Trials_Notes_part2" : "You can follow the link above in order to get other builds and/or pots information and tips."
    }
}